build:
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    tags:
        - c2-maker
    script:
        - "make clean"
        - "make VERSION=$CI_JOB_ID"
    artifacts:
        expire_in: 100 years
        paths:
            - out/menu.bin
            - out/menu.map
            - out/menu.elf
