build:
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
    tags:
        - c2-maker
    script:
        - "rm -rf iapetus-build newlib-build"
        - "make clean"
        - "make VERSION=$CI_COMMIT_REF_SLUG"
        - 'cd out; NUM=$(if [ "${CI_COMMIT_REF_SLUG}" -eq "${CI_COMMIT_REF_SLUG}" ]; then printf %06d ${CI_COMMIT_REF_SLUG}; else echo ${CI_COMMIT_REF_SLUG}; fi); zip satiator_menu${NUM}.zip menu.bin; mv satiator_menu${NUM}.zip ..'
    artifacts:
        expire_in: 100 years
        paths:
            - out/menu.bin
            - out/menu.map
            - out/menu.elf
            - satiator_menu*.zip

deploy:
    stage: deploy
    only:
      - /^\d+$/
    script:
      - 'ln -sf satiator_menu*.zip latest.zip'
      - 'rsync -l -e "ssh -i $SSH_DEPLOY_KEY" latest.zip satiator_menu*.zip CHANGELOG web-deploy@info.satiator.net:menu/'
